### ISSUE TITLE
Click outside to close

### ISSUE THREAD

**Issue by nyorbee** [popeen/Classic-Volume-Mixer#11]
Hi, app is great, 100 times better than W11 stock one. But could you add an option to close dialog box, when clicking somewhere outside? To not have to click on X?

**Comment by popeen** [comment]
To implement something like this I would need to listen to every click all the time, that's not something I want the app to do so unfortunately no.

If someone can think of another way to do it that don't require that I will gladly merge it

**Comment by impeeza** [comment]
I don't know how to do it, but on Windows almost all windows have a method called "on lost focus" which is invoked when the user click outside the window.
