### ISSUE TITLE
Option not have using Classic Mixer

### ISSUE THREAD

**Issue by nathanparra** [popeen/Classic-Volume-Mixer#18]
Hi, see this problem, maybe can fix
https://youtu.be/xTEdwdyqAsk

and change of subject
Taking advantage of this topic, is it possible to add a dark theme for classic mixer?

**Comment by graefjk** [comment]
Adding a dark theme will probably not be possible, as this programm just adds the icon. The mixer that opens is just the old windows mixer and we have no influence on how this looks.
