### ISSUE TITLE
Being able to select output device

### ISSUE THREAD

**Issue by Thrallix** [popeen/Classic-Volume-Mixer#19]
Hello.

I don't know if i'm doing something wrong, but as far as i can recall, i used to be able to select my output device (switch from headset to speakers etc.) and now that dropdown is missing.

Is this a planned feature, is it already implemented or is it just not going to happen?
I'd love to know, thank you :)

**Comment by graefjk** [comment]
You can switch your standart output device by selecting "Sound" in the menu, then right clicking the desired Devices and choosing "set as standart device".
I don't recall having the devices listed in a dropdown for switching standart output devices, what Version of Windows are you reffering to?

**Comment by kimiroo** [comment]
Windows 10, perhaps?
Even if so, Windows's classic volume mixer has no functionality of switching output device built-in. You would have to write a completely new standalone mixer app with output device switching features built-in.
![image](https://github.com/popeen/Classic-Volume-Mixer/assets/43537287/42690097-05c4-4575-a6eb-2fef9ebd7d64)
Maybe you got confused with classic mixer's device list dropdown posted above. That dropdown is meant for controlling the volume mixers of per output devices, not switching the default output device.

**Comment by kimiroo** [comment]
Perhaps implement output device selection like this?
![스크린샷 2023-12-23 214114](https://github.com/popeen/Classic-Volume-Mixer/assets/43537287/bd42a0c8-4bfb-486c-8b41-9ff4491a37c2)

**Comment by popeen** [comment]
Fixed in #23
