### ISSUE TITLE
(Feature request) Being able to save config after restart

### ISSUE THREAD

**Issue by kimiroo** [popeen/Classic-Volume-Mixer#21]
Everytime I restart my computer, I would have to right click and set the configs and it's kind of annoying.

Certain apps (mainly fullscreen apps like games) keeps focusing itself, making volume mixer go away instantly, so I have uncheck "Close by clicking outside the window". But since the the app doesn't save and load config on startup, I would have to set the config everytime I startup my machine.

**Comment by popeen** [comment]
Fixed in #22
