### ISSUE TITLE
Change tray icon

### ISSUE THREAD

**Issue by geextahslex** [popeen/Classic-Volume-Mixer#24]
Hi, would it be possible to change the icon of the program? To look like the stock Windows 10 icon?
![mixer icon](https://github.com/popeen/Classic-Volume-Mixer/assets/139760266/51940383-0246-4b47-8272-65969ea3376c)

Thank you for any answer :)

**Comment by impeeza** [comment]
I don't think so, because that is a copyrighted resource.  unless the program uses the resource in the computer.

**Comment by geextahslex** [comment]
The tray icon also doesn't show if the sound is muted 
![muted icon](https://github.com/popeen/Classic-Volume-Mixer/assets/139760266/0d4783db-e166-4a19-a277-35eee3be1b6f)

**Comment by popeen** [comment]
Fixed in #26
