### ISSUE TITLE
Icon is barely visible when using light mode.

### ISSUE THREAD

**Issue by fishnet37222** [popeen/Classic-Volume-Mixer#29]
I always use Windows in light mode.  I just installed this app and noticed that the icon it added was very hard to see (see the screenshot below).  It would be helpful if you could provide an option to switch to a black icon.

![image](https://github.com/user-attachments/assets/0dabecb2-b37d-4ede-b522-6c6557618df0)

**Comment by popeen** [comment]
Great catch, added a setting for it that will be included in the next release
